### ISSUE TITLE
Add GTK 3.20 support

### ISSUE THREAD

**Issue by capitanx** [Elbullazul/Redmond-Themes#2]
The current themes don't work in GTK 3.20 due the CSS changes.
https://blogs.gnome.org/mclasen/2015/11/20/a-gtk-update/

**Comment by ghost** [comment]
is ambiance ported to gtk 3.20. a pure css (not scss) based port to gtk3 is needed.

Please do try to ask raveit/ulbricht from mate themes for an idea.dont know him but it might be useful to ask him for a hint. think its time to wait a bit. 
3.20 changes are heavy and the number of themes for 3.20 
decreased for a reason.

**Comment by Elbullazul** [comment]
@capitanx sorry for the late reply, hadn't seen these issues.

just like @bluedxca93 says, 3.20 break a lot of things and I don't even have a stable code base to work on (Windows 10 for 3.20 is on beta and still lots of substitutions needed)

I'll let you know whenever I've finished working on the base code, and then count maybe two weeks till all themes are compatible

hope gnome 3.22 won't break themes harder than 3.20 did...

**Comment by ghost** [comment]
@elbulazull check my port script from bluedxca93 18/20 .it substitutes a lot of classes already.trained it against adwaita and traditional ok.

also use GTK_DEBUG=interactive gtkapplication name.

**Comment by ghost** [comment]
@Elbullazul now loaded up aero expirimental based on 3.20 . ccbyncnd . for heavy mods cc by nc sa

**Comment by Elbullazul** [comment]
@bluedxca93 I just checked, aero works (almost flawlessly)! Just one more thing, the notebooks are the same whatever their state : 
![fedora 24 alpha aero](https://cloud.githubusercontent.com/assets/15310985/16129786/4ed1a144-33d4-11e6-89ac-b5dd82f43ac7.png)

**Comment by ghost** [comment]
@Elbullazul
noted some changes i'll add to my porting script.There are some bugs
left in the script and the theme. The script can't make a full port
actually.
notebook and toolbar/headerbar as well as one menu type needs some
future improvement. But it works stable enough to work a bit with
it.One bug that really is anoing is selected
foreground/background.Scrollbar is also not final but the progress is
not bad..

**Comment by Elbullazul** [comment]
@bluedxca93 yeah, it's definetely better than ![Metadata](https://cloud.githubusercontent.com/assets/9755486/14407840/db868e06-fea5-11e5-8e43-62d3f5b758f0.png)

progressbar is actually pretty nice, I'm fixing mine with padding

I'm kind of annoyed that gnome 3.22 is coming out in september already and we're just getting started with themes...

**Comment by ghost** [comment]
im only doing aero for 3.20
no need to port other themes to. it. 3.18 is in an ubuntu lts release. 3.22 will delete some more gtk classes . Itll be more seigned for scss. However scss is only good for logical mostly flat skins.

**Comment by Elbullazul** [comment]
@bluedxca93 I had a look at the original adwaita css and scss files

man, scss was awful long and had WAY MORE styling elements (plus colors are defined in a weird manner)

**Comment by ghost** [comment]
@Elbullazul some of these are missing, but adwaita is also missing some style elements. But its  the same on gtk 18 adwaita and ambiance. the scss layout also generates sometimes states like checked:focus:hover:backdrop. where is that necessary?

**Comment by Elbullazul** [comment]
as far as I know, this looks OK to start porting the Redmond Collection to 3.20, right?

![screenshot from 2016-06-17 08-17-14](https://cloud.githubusercontent.com/assets/15310985/16150274/2841e3f0-3464-11e6-9540-a87b9123f63b.png)

**Comment by ghost** [comment]
@elbullazul It looks nice. Problem might be that this  works definitely well on 8 and 10 but aero luna etc. possibly not. what codebase did you use?.
send now ravefinity a patched ambiance version.Ambiance needs rewrite.can you send me css bundled out of scss from numix?

**Comment by Elbullazul** [comment]
@bluedxca93 I used the original adwaita theme (lots of gradients), so I think it should behave normally

distributing the colors will be a little harder

I'll have a look at the numix code and come back later

**Comment by ghost** [comment]
@elbullazul scale.vertical slider instead of scale slider.vertical.
hope it helps...

**Comment by Elbullazul** [comment]
@bluedxca93 I'm seriously considering to port the themes instead of doing a compete rewrite.  I'll let you know if I write patches for known issues. 

P. S.  The text selected color issue may be related to the textview class or tag

**Comment by ghost** [comment]
https://github.com/bluedxca93/aero-experimental will be updated soon.

textview issue found and fixed.
notebook fixed a bit more.(im not finished with it.).

maybe you can write changes in this way whenever possible:

s/original_string/patched_string/g

and change
. > .
: > :
newline in string > \n

regards bluedxca93

**Comment by Elbullazul** [comment]
we started porting the Windows 3 theme to 3.20

lots of errors as of now...

**Comment by Elbullazul** [comment]
that went fast! almost flawless theme now!
![screenshot from 2016-09-19 15-57-49](https://cloud.githubusercontent.com/assets/15310985/18652392/c692bb24-7e97-11e6-82ce-0cadf472693f.png)

**Comment by ghost** [comment]
looks good.

**Comment by capitanx** [comment]
Thank you a lot. It works perfect. :)
Can be win95 the next?

**Comment by Elbullazul** [comment]
@capitanx we're working on it, it`s almost finished

**Comment by Elbullazul** [comment]
@capitanx Windows 9x for 3.20 is now pushed to the repo, haven`t got time to package it up

enjoy!

**Comment by ghost** [comment]
@elbullazul congrats for getting it up. You know ambiance-aero is vista
like . Question Should i make luna too , or focus on ice theme set first??

**Comment by Elbullazul** [comment]
I don`t know, luna is already available (petrucci4prez)

I would say, port ice first, then luna

**Comment by ghost** [comment]
okay thx,
i will start most probably on saturday/sunday. i can`t before cause of
school/job.

**Comment by cinnamoner** [comment]
> congrats for getting it up.

@Elbullazul Interesting formulation :)

**Comment by cinnamoner** [comment]
> I'm kind of annoyed that gnome 3.22 is coming out in september already and ...

@Elbullazul Why the heck this continuous upversioning. Do they enjoy torturing people? I don't get it. What good comes from that? I'm stupid I guess.

**Comment by Elbullazul** [comment]
@bluedxca93 how finished do you think the aero theme is?

**Comment by ghost** [comment]
@elbullazul
check it on 3.20 and you ll see. just make a screen if you found a bug.

**Comment by cinnamoner** [comment]
> Can be win95 the next?

@Elbullazul Can it be Vista after win95? Just proceed as you see fit. I trust you. Do you need screeshots from a 1080 featuring the latest iteration side by side with the real thing? If that helps, I'll provide.

**Comment by cinnamoner** [comment]
>  It works perfect. :)

@capitanx Nothing made by a human works perfectly. Just reasonably well :)

**Comment by cinnamoner** [comment]
Guys, do you happen to know a distro based on Xenial and featuring Cinnamon, other than Mint?

**Comment by Elbullazul** [comment]
@cinnamoner cinnamon is built for mint, and except for arch, I don`t know how it could behave

I just know that fedora 24 has cinnamon in its repos and it`s supposed to work better than the one used in ubuntu

@bluedxca93 I would add some shadows to the window frames. Aero looks too flat / disorganized without them

**Comment by Elbullazul** [comment]
@cinnamoner  I`m waiting for @bluedxca93 to finish porting aero. Then maybe I can attack the vista theme

**Comment by ghost** [comment]
@elbullazul make a screen without and do and do edit this image to how it
should look. then im trying my best to do that.

regards bluedxca93

**Comment by Elbullazul** [comment]
## ex.

![aero-metacity](https://cloud.githubusercontent.com/assets/15310985/16129786/4ed1a144-33d4-11e6-89ac-b5dd82f43ac7.png)

vs

![aero-gnome](https://cloud.githubusercontent.com/assets/15310985/18602855/54ca65da-7c32-11e6-8427-38dd517dbbf7.png)

**Comment by ghost** [comment]
vs newest version 3.20.
![gtk3-widget-factory-lastest](https://cloud.githubusercontent.com/assets/4351663/18756881/d8d40502-80f1-11e6-8fec-428f9cd3e03a.jpg)

As you can see it looks almost perfect. But its newest version from github and not your earlier setup.

**Comment by cinnamoner** [comment]
@bluedxca93 Looks good.

**Comment by cinnamoner** [comment]
@Elbullazul Said you were waiting for bluedxca93 to port than you would maybe attack Vista. Okay, might have some extra Metacity for you to include. The theme looks better with graphite instead of Blue. If you've got Vista then you know what I'm talking about. If not I'll show.

**Comment by Elbullazul** [comment]
@bluedxca93 correct, I must have forgotten to update it

it looks nice! Can I propose you change the text-color of the titlebuttons to white with a text-shadow, so the icons look like windows aero?

![rsz_0-bymvk7zo-21](https://cloud.githubusercontent.com/assets/15310985/18758106/ae07d11e-80c4-11e6-8cda-35c2c325e529.png)

**Comment by cinnamoner** [comment]
@Elbullazul Would you bet on Manjaro Cinnamon or Apricity Cinnamon? :):)

**Comment by ghost** [comment]
@elbullazul of course yes, just write me how and ill add that feature!

**Comment by Elbullazul** [comment]
@cinnamoner I would go with apricity, it looks neater than manjaro

@bluedxca93 something like

``` css
.titlebar .titlebutton {
    color: white;
    text-shadow: 0 0 2px black;
}
```

**Comment by cinnamoner** [comment]
> it looks nice ...

@bluedxca93 That's what I'm talking about. But I would have it with graphite. Just carry on, I can replace  the colour on my own. The rest is what matters. Well done.

**Comment by cinnamoner** [comment]
And is Arch. Pure. That was the answer I was waiting for.

**Comment by cinnamoner** [comment]
Man, I like what I see on this thread.

**Comment by ghost** [comment]
@elbullazul / @feren now early port of ice online on github, maybe make a
screenshot.
regards bluedxca93

**Comment by cinnamoner** [comment]
@Elbullazul Sorry, I'm not supposed to talk much but the Vista remains the best for me !

**Comment by cinnamoner** [comment]
![ae07d11e-80c4-11e6-8cda-35c2c325e529](https://cloud.githubusercontent.com/assets/15638605/18891745/4f2eb032-850f-11e6-8dd6-b47d9a5611f8.png)
We're still discussing this. It shows you're not on Vista. I must post those shots once and for all.

**Comment by Elbullazul** [comment]
@cinnamoner please post them in a new issue report. may prove usfeful ;)

**Comment by dominichayesferen** [comment]
@Elbullazul Did you get the problem I posted on Gitter about the solid block?
If you want to see what I mean by it:

```
sudo add-apt-repository ppa:elementary-os/stable
sudo apt update
sudo apt remove shotwell*
sudo apt install pantheon-photos
```

Then run Photos and choose a theme like Embedded as GTK

**Comment by Elbullazul** [comment]
fixed on latest commit

**Comment by dominichayesferen** [comment]
@Elbullazul It also affects macOS so if you haven't updated that one yet...

**Comment by Elbullazul** [comment]
I did

**Comment by dominichayesferen** [comment]
Nope, still happens here on the latest Git version of it: (Cinnamon Stable)
![screenshot from 2016-09-29 06-38-09](https://cloud.githubusercontent.com/assets/11057934/18943475/62791820-860f-11e6-85c4-f19771e4c168.png)

**Comment by cinnamoner** [comment]
@Elbullazul Sure thing. You'll get them as whished pretty soon. The screenies that is. And more.

**Comment by Elbullazul** [comment]
![screenshot_2016-09-29_19-04-46](https://cloud.githubusercontent.com/assets/15310985/18975374/a2793f96-8677-11e6-9658-47449af74be5.png)

pushing commit in short

**Comment by cinnamoner** [comment]
@Elbullazul I like the slider in a groove but no need for those + -  magniicons. Right above.

**Comment by Elbullazul** [comment]
except for the vista theme, every other theme has 3.20 compatibility, so I'm closing it, since @bluedxca93 has the [aero theme](https://github.com/bluedxca93/aero-experimental) which looks OK for it to be used with the vista theme
